kind: pipeline
type: docker
name: default

environment:
  version: 0.0.1
steps:
- name: build-frontend
  image: node:alpine
  commands:
  - node --version
  # - npm install --global yarn
  - cd frontend
  - ls -la
  - yarn --version
  - yarn
  - yarn build --outDir /result/static/
  - ls -la /result
  volumes:
  - name: result
    path: /result

- name: build-backend
  image: rust:latest
  environment:
    CARGO_HOME: /var/cache/drone/cargo
  commands:
  - cargo --version
  - cd backend
  - cargo build --release
  - ls -la ./target/release
  - cp ./target/release/backend /result
  - ls -la /result
  volumes:
  - name: result
    path: /result
  - name: rust_cache
    path: /var/cache/drone/cargo

- name: build docker
  image: docker
  environment:
    CI_REGISTRY_USER:
      from_secret: CI_HUB_USER
    CI_REGISTRY_PASSWORD:
      from_secret: CI_HUB_PASSWORD
    CI_REGISTRY:
      from_secret: CI_REGISTRY
  commands:
  - export VERSION=$version
  - cp -r /result ./
  - chmod a+x result/backend
  - ls -la result
  - docker build -t thisseanzhang/gpt-ui:$${VERSION} .
  - docker images
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - docker push thisseanzhang/gpt-ui:$${VERSION}
  - docker logout $CI_REGISTRY
  - docker rmi thisseanzhang/gpt-ui:$${VERSION}
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: result
    path: /result


volumes:
- name: result
  temp: {}
- name: docker
  host:
    path: /var/run/docker.sock
- name: rust_cache
  host:
    path: /tmp/rust_cache
node:
  la24: latest

